site_name: geoarches

# Repository
repo_name: INRIA/geoarches
repo_url: https://github.com/INRIA/geoarches

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking

plugins:
    - mkdocs-jupyter

# Page tree
nav:
  - Home: index.md
  - Getting started: 
      - Installation: getting_started/installation.md
      - Using geoarches modules: getting_started/using_geoarches.md
  - User Guide: user_guide.md
  - Contributing:
      - Contribute to project: contributing/contribute.md
      - Report bug or feature request: bug.md
  - ArchesWeather: 
      - Run: archesweather/run.ipynb
      - Train: archesweather/train.md

