era5_deterministic_metrics:
  _target_: geoarches.metrics.deterministic_metrics.Era5DeterministicMetrics
  surface_variables: ${stats.module.variables.surface}
  level_variables: ${stats.module.variables.level}
  pressure_levels: ${stats.module.levels}
  lead_time_hours: ${dataloader.dataset.lead_time_hours}