dataset: 
  _target_: geoarches.dataloaders.era5.Era5Forecast
  path: data/era5_240/full/
  lead_time_hours: 24
  multistep: ${oc.select:module.rollout_iterations,1}
  norm_scheme: pangu
  load_prev: True

validation_args:
  multistep: ${oc.select:module.validation.rollout_iterations,1}

test_args:
  multistep: ${module.inference.rollout_iterations}